/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Dia3;

import java.util.Scanner;

public class App {
   

    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);
        
        System.out.println("Digite a quantidade de quilômetros percorridos:");
        float km = leitor.nextFloat();
        
        System.out.println("Digite o total de litros de gasolina usados:");
        float litros = leitor.nextFloat();
        
        float consumoMedio = km/litros;
        
        System.out.println("O consumo médio de gasolina foi de " + consumoMedio);
                
                
        
        
        
    }
}
